// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/your-org/rclone-sync-hub"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/fs/subdirs": {
            "get": {
                "description": "根据传入的本地路径，返回该路径下所有一级子文件夹（不包含文件）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filesystem"
                ],
                "summary": "获取指定路径下的子文件夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本地起始路径，如 D:/data 或 /data/local",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.FSSubDirListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rclone/configs": {
            "get": {
                "description": "调用 ` + "`" + `rclone config show` + "`" + ` 并解析出 remote 名称与类型，过滤掉敏感字段",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rclone"
                ],
                "summary": "获取 rclone remote 配置列表",
                "responses": {
                    "200": {
                        "description": "items 为 remote 列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "error 为错误信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks": {
            "get": {
                "description": "按状态筛选并分页返回上传任务，不传 status 时返回全部",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "分页获取上传任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务状态: pending|running|success|failed，空为全部",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从 1 开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items 为任务列表，total 为总条数",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "error 为错误信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "新建一个上传任务（默认状态为待上传）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "创建上传任务",
                "parameters": [
                    {
                        "description": "任务配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.UploadTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/delete": {
            "post": {
                "description": "对传入的任务 ID 列表执行删除操作，running 状态的任务会失败并给出原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量删除上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/pause": {
            "post": {
                "description": "对传入的任务 ID 列表执行暂停操作，running 状态的任务会失败并给出原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量暂停上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/retry": {
            "post": {
                "description": "对传入的任务 ID 列表执行重试操作，running 状态的任务会失败并给出原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量重试上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}": {
            "delete": {
                "description": "上传中的任务不可删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "删除上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/pause": {
            "post": {
                "description": "上传中的任务不可暂停",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "暂停上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/watch-folders": {
            "get": {
                "description": "按状态分页获取监听文件夹列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "列出监听文件夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态: detecting|watching|stopped|paused|error",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从 1 开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items 为列表，total 为总数",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "新增一个被监听并同步到指定 rclone remote 的本地目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "创建监听文件夹",
                "parameters": [
                    {
                        "description": "监听文件夹配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.WatchFolderCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.WatchFolder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/watch-folders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "获取监听文件夹详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听文件夹 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.WatchFolder"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "更新监听文件夹",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听文件夹 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容（全部可选）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.WatchFolderUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.WatchFolder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "删除监听文件夹",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听文件夹 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.FSSubDir": {
            "type": "object",
            "properties": {
                "has_sub_dirs": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "internal_api.FSSubDirListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.FSSubDir"
                    }
                }
            }
        },
        "internal_api.TaskBatchReq": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "description": "任务 ID 列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_api.TaskCreateReq": {
            "type": "object",
            "required": [
                "local_path",
                "remote_name",
                "remote_path"
            ],
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "local_path": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_path": {
                    "type": "string"
                },
                "watch_folder_id": {
                    "type": "integer"
                },
                "watch_folder_name": {
                    "type": "string"
                }
            }
        },
        "internal_api.WatchFolderCreateReq": {
            "type": "object",
            "required": [
                "local_path",
                "name",
                "remote_name",
                "remote_path"
            ],
            "properties": {
                "local_path": {
                    "type": "string"
                },
                "max_depth": {
                    "description": "可选，0 表示不限制",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_path": {
                    "type": "string"
                },
                "scan_interval_seconds": {
                    "description": "可选，默认 300",
                    "type": "integer"
                },
                "sync_type": {
                    "description": "可选，默认 local_to_remote",
                    "type": "string"
                }
            }
        },
        "internal_api.WatchFolderUpdateReq": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "local_path": {
                    "type": "string"
                },
                "max_depth": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_path": {
                    "type": "string"
                },
                "scan_interval_seconds": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "sync_type": {
                    "type": "string"
                }
            }
        },
        "rclone-sync-hub_internal_model.FileRecord": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fileHash": {
                    "description": "可选，用于去重",
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "localPath": {
                    "type": "string"
                },
                "relativePath": {
                    "description": "相对扫描根目录的路径",
                    "type": "string"
                },
                "remotePath": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "uploadedAt": {
                    "type": "string"
                }
            }
        },
        "rclone-sync-hub_internal_model.UploadTask": {
            "type": "object",
            "properties": {
                "accumulatedFailures": {
                    "description": "累计失败次数（便于分析）",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "durationSeconds": {
                    "description": "时间维度",
                    "type": "integer"
                },
                "errorMsg": {
                    "description": "最后一次错误信息",
                    "type": "string"
                },
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "fileRecord": {
                    "description": "关联（不参与表结构，仅查询用）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.FileRecord"
                        }
                    ]
                },
                "fileRecordID": {
                    "type": "integer"
                },
                "fileSize": {
                    "description": "文件信息",
                    "type": "integer"
                },
                "finishedAt": {
                    "description": "上传结束时间",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastProgressAt": {
                    "description": "最近一次进度上报时间",
                    "type": "string"
                },
                "lastStatusAt": {
                    "description": "最近一次状态变更时间",
                    "type": "string"
                },
                "localPath": {
                    "description": "文件本地路径",
                    "type": "string"
                },
                "log": {
                    "description": "日志与分析",
                    "type": "string"
                },
                "progress": {
                    "description": "上传进度（0-100）",
                    "type": "number"
                },
                "remoteName": {
                    "description": "上传网盘（remote 名称）",
                    "type": "string"
                },
                "remotePath": {
                    "description": "上传路径",
                    "type": "string"
                },
                "retryCount": {
                    "description": "重试次数",
                    "type": "integer"
                },
                "speed": {
                    "description": "最近一次上报的速度（bytes/s）",
                    "type": "integer"
                },
                "startedAt": {
                    "description": "上传开始时间",
                    "type": "string"
                },
                "status": {
                    "description": "状态与进度",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "watchFolderID": {
                    "description": "归属与标识",
                    "type": "integer"
                },
                "watchFolderName": {
                    "description": "所属监听文件夹名称快照",
                    "type": "string"
                }
            }
        },
        "rclone-sync-hub_internal_model.WatchFolder": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "enabled": {
                    "description": "是否启用该监听",
                    "type": "boolean"
                },
                "failedFileCount": {
                    "description": "累计上传失败文件数",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lastActiveAt": {
                    "description": "最近有文件变更 / 上传的时间",
                    "type": "string"
                },
                "lastError": {
                    "description": "最近一次错误信息（便于排查）",
                    "type": "string"
                },
                "lastScanAt": {
                    "description": "最近一次扫描时间",
                    "type": "string"
                },
                "lastSyncAt": {
                    "description": "最近一次同步时间",
                    "type": "string"
                },
                "localPath": {
                    "description": "注意：MySQL InnoDB 单列索引最大 3072 字节（utf8mb4 约 768 字符），且 LocalPath 上有唯一索引，因此长度限制为 768。",
                    "type": "string"
                },
                "maxDepth": {
                    "description": "最大监听深度，0 表示不限制",
                    "type": "integer"
                },
                "name": {
                    "description": "基本配置",
                    "type": "string"
                },
                "nextScanAt": {
                    "description": "预计下一次扫描时间（可选）",
                    "type": "string"
                },
                "remoteName": {
                    "description": "rclone remote 名称",
                    "type": "string"
                },
                "remotePath": {
                    "description": "远端路径",
                    "type": "string"
                },
                "scanIntervalSeconds": {
                    "description": "配置相关扩展",
                    "type": "integer"
                },
                "status": {
                    "description": "状态信息",
                    "type": "string"
                },
                "syncType": {
                    "description": "同步类型",
                    "type": "string"
                },
                "totalFileCount": {
                    "description": "统计维度（便于分析与展示）",
                    "type": "integer"
                },
                "totalFileSize": {
                    "description": "当前已知文件总大小（字节）",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "uploadedBytes": {
                    "description": "累计已上传字节数",
                    "type": "integer"
                },
                "uploadedFileCount": {
                    "description": "累计已成功上传文件数",
                    "type": "integer"
                },
                "windowUploadedBytes": {
                    "description": "窗口内上传字节数",
                    "type": "integer"
                },
                "windowUploadedFiles": {
                    "description": "最近一段时间的窗口统计（可用于展示趋势）",
                    "type": "integer"
                }
            }
        },
        "rclone-sync-hub_internal_service.TaskBatchResult": {
            "type": "object",
            "properties": {
                "failed": {
                    "description": "taskID -\u003e error message",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ok_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rclone Sync Hub API",
	Description:      "文件上传调度系统 REST API：任务列表、扫描、重试、统计等",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
