// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Project repository",
            "url": "https://github.com/zane626/rclone-sync-hub-go-backend"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/analytics/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回概览数字、按状态/按监听文件夹/按时间趋势的图表数据，以及最近任务与失败任务列表，供数据分析页一次拉取",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "数据分析仪表盘",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "趋势图天数，默认 7",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.DashboardData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/audit-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "获取操作审计日志",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取认证配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "用户名和密码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "events"
                ],
                "summary": "订阅任务实时事件",
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/fs/subdirs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据传入的本地路径，返回该路径下所有一级子文件夹（不包含文件）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filesystem"
                ],
                "summary": "获取指定路径下的子文件夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本地起始路径，如 /volumes",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.FSSubDirListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "兼容健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/health/live": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "存活检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/health/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "就绪检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rclone/configs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "调用 ` + "`" + `rclone listremotes --long` + "`" + ` 获取 remote 名称与类型，不读取配置密钥",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rclone"
                ],
                "summary": "获取 rclone remote 配置列表",
                "responses": {
                    "200": {
                        "description": "items 为 remote 列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "error 为错误信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/scan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "异步触发全部启用目录扫描",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    }
                }
            }
        },
        "/api/scan-runs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "获取扫描历史",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听目录 ID；0 为全部",
                        "name": "watch_folder_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "获取任务状态统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按状态筛选并分页返回上传任务，不传 status 时返回全部；keyword 对 watch_folder_name/file_name/local_path/remote_name/remote_path 模糊查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "分页获取上传任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务状态: pending|running|success|failed|paused|canceled，空为全部",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词：对所属文件夹名/文件名/本地路径/网盘名/上传路径模糊查询",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从 1 开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items 为任务列表，total 为总条数",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "error 为错误信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新建一个上传任务（默认状态为待上传）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "创建上传任务",
                "parameters": [
                    {
                        "description": "任务配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.UploadTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量取消上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对传入的任务 ID 列表执行删除操作，running 状态的任务会失败并给出原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量删除上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对传入的任务 ID 列表执行暂停操作，running 状态的任务会失败并给出原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量暂停上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/batch/retry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对传入的任务 ID 列表执行重试操作，running 状态的任务会失败并给出原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "批量重试上传任务",
                "parameters": [
                    {
                        "description": "任务 ID 列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.TaskBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.TaskBatchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "获取上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.UploadTask"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传中的任务不可删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "删除上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "等待中的任务立即取消；运行中的任务在 worker 心跳后终止 rclone 进程",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "取消上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按任务 ID 返回 upload_logs 中的日志列表，支持 limit 限制条数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "获取任务上传日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "最多返回条数，默认 500",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/rclone-sync-hub_internal_model.UploadLog"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传中的任务不可暂停",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "暂停上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/retry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "重试上传任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/watch-folders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按状态分页获取监听文件夹列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "列出监听文件夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态: detecting|watching|stopped|paused|error",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词：对 name/local_path/remote_name/remote_path 模糊查询",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从 1 开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items 为列表，total 为总数",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新增一个被监听并同步到指定 rclone remote 的本地目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "创建监听文件夹",
                "parameters": [
                    {
                        "description": "监听文件夹配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.WatchFolderCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.WatchFolder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/watch-folders/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "获取监听文件夹详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听文件夹 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.WatchFolder"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "更新监听文件夹",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听文件夹 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容（全部可选）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.WatchFolderUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.WatchFolder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "原子取消该目录的未完成任务并解除文件快照归属；活动扫描期间返回冲突",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watch-folders"
                ],
                "summary": "删除监听文件夹",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "监听文件夹 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.FSSubDir": {
            "type": "object",
            "properties": {
                "has_sub_dirs": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "internal_api.FSSubDirListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.FSSubDir"
                    }
                }
            }
        },
        "internal_api.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 1024
                },
                "username": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_api.TaskBatchReq": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "description": "任务 ID 列表",
                    "type": "array",
                    "maxItems": 1000,
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_api.TaskCreateReq": {
            "type": "object",
            "required": [
                "local_path",
                "remote_name",
                "remote_path"
            ],
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "local_path": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_path": {
                    "type": "string"
                },
                "watch_folder_id": {
                    "type": "integer"
                },
                "watch_folder_name": {
                    "type": "string"
                }
            }
        },
        "internal_api.WatchFolderCreateReq": {
            "type": "object",
            "required": [
                "local_path",
                "name",
                "remote_name",
                "remote_path"
            ],
            "properties": {
                "filter_keywords": {
                    "description": "可选，多行关键字，换行分隔，扫描时模糊匹配排除",
                    "type": "string"
                },
                "local_path": {
                    "type": "string"
                },
                "max_depth": {
                    "description": "可选，0 表示不限制",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_path": {
                    "type": "string"
                },
                "scan_interval_seconds": {
                    "description": "可选，默认 300",
                    "type": "integer"
                },
                "sync_type": {
                    "description": "可选，默认 local_to_remote",
                    "type": "string"
                }
            }
        },
        "internal_api.WatchFolderUpdateReq": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "filter_keywords": {
                    "type": "string"
                },
                "local_path": {
                    "type": "string"
                },
                "max_depth": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_path": {
                    "type": "string"
                },
                "scan_interval_seconds": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "sync_type": {
                    "type": "string"
                }
            }
        },
        "rclone-sync-hub_internal_model.FileRecord": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fileHash": {
                    "description": "可选，内容哈希用于强校验",
                    "type": "string"
                },
                "fileModTime": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "fingerprint": {
                    "description": "size + mtime 的快速元数据指纹",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastSeenAt": {
                    "type": "string"
                },
                "localPath": {
                    "type": "string"
                },
                "missingAt": {
                    "description": "最近一次完整扫描确认文件已不存在",
                    "type": "string"
                },
                "relativePath": {
                    "description": "相对扫描根目录的路径",
                    "type": "string"
                },
                "remoteName": {
                    "type": "string"
                },
                "remotePath": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "uploadedAt": {
                    "type": "string"
                },
                "watchFolderID": {
                    "type": "integer"
                }
            }
        },
        "rclone-sync-hub_internal_model.UploadLog": {
            "type": "object",
            "properties": {
                "bytesDone": {
                    "type": "integer"
                },
                "bytesTotal": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "percent": {
                    "type": "number"
                },
                "speed": {
                    "description": "bytes/s",
                    "type": "integer"
                },
                "taskID": {
                    "type": "integer"
                }
            }
        },
        "rclone-sync-hub_internal_model.UploadTask": {
            "type": "object",
            "properties": {
                "accumulatedFailures": {
                    "description": "累计失败次数（便于分析）",
                    "type": "integer"
                },
                "cancelRequestedAt": {
                    "description": "运行中任务的取消请求",
                    "type": "string"
                },
                "canceledAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "durationSeconds": {
                    "description": "时间维度",
                    "type": "integer"
                },
                "errorMsg": {
                    "description": "最后一次错误信息",
                    "type": "string"
                },
                "fileFingerprint": {
                    "description": "创建任务时的文件元数据指纹",
                    "type": "string"
                },
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "fileRecord": {
                    "description": "关联（不参与表结构，仅查询用）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rclone-sync-hub_internal_model.FileRecord"
                        }
                    ]
                },
                "fileRecordID": {
                    "type": "integer"
                },
                "fileSize": {
                    "description": "文件信息",
                    "type": "integer"
                },
                "finishedAt": {
                    "description": "上传结束时间",
                    "type": "string"
                },
                "heartbeatAt": {
                    "description": "最近一次租约心跳",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "idempotencyKey": {
                    "description": "nullable，兼容旧数据并防止重复建任务",
                    "type": "string"
                },
                "lastProgressAt": {
                    "description": "最近一次进度上报时间",
                    "type": "string"
                },
                "lastStatusAt": {
                    "description": "最近一次状态变更时间",
                    "type": "string"
                },
                "leaseExpiresAt": {
                    "description": "租约到期时间",
                    "type": "string"
                },
                "leaseOwner": {
                    "description": "当前 worker 实例",
                    "type": "string"
                },
                "localPath": {
                    "description": "文件本地路径",
                    "type": "string"
                },
                "log": {
                    "description": "日志与分析",
                    "type": "string"
                },
                "nextRetryAt": {
                    "description": "下次允许领取时间",
                    "type": "string"
                },
                "priority": {
                    "description": "数值越大优先级越高",
                    "type": "integer"
                },
                "progress": {
                    "description": "上传进度（0-100）",
                    "type": "number"
                },
                "remoteName": {
                    "description": "上传网盘（remote 名称）",
                    "type": "string"
                },
                "remotePath": {
                    "description": "上传路径",
                    "type": "string"
                },
                "retryCount": {
                    "description": "已领取执行次数（包含首次）",
                    "type": "integer"
                },
                "speed": {
                    "description": "最近一次上报的速度（bytes/s）",
                    "type": "integer"
                },
                "startedAt": {
                    "description": "上传开始时间",
                    "type": "string"
                },
                "status": {
                    "description": "状态与进度",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "watchFolderID": {
                    "description": "归属与标识",
                    "type": "integer"
                },
                "watchFolderName": {
                    "description": "所属监听文件夹名称快照",
                    "type": "string"
                }
            }
        },
        "rclone-sync-hub_internal_model.WatchFolder": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "enabled": {
                    "description": "是否启用该监听",
                    "type": "boolean"
                },
                "failedFileCount": {
                    "description": "累计上传失败文件数",
                    "type": "integer"
                },
                "filterKeywords": {
                    "description": "过滤关键字，多行存储，每行一个；路径或文件名包含任一关键字（模糊匹配）则排除",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastActiveAt": {
                    "description": "最近有文件变更 / 上传的时间",
                    "type": "string"
                },
                "lastError": {
                    "description": "最近一次错误信息（便于排查）",
                    "type": "string"
                },
                "lastScanAt": {
                    "description": "兼容字段：最近一次扫描开始时间",
                    "type": "string"
                },
                "lastScanDurationMs": {
                    "description": "最近一次扫描耗时（毫秒）",
                    "type": "integer"
                },
                "lastScanFinishedAt": {
                    "description": "最近一次扫描结束时间（无论成功失败）",
                    "type": "string"
                },
                "lastScanStartedAt": {
                    "description": "最近一次扫描开始时间",
                    "type": "string"
                },
                "lastScanSuccessAt": {
                    "description": "最近一次成功扫描结束时间",
                    "type": "string"
                },
                "lastSyncAt": {
                    "description": "最近一次同步时间",
                    "type": "string"
                },
                "localPath": {
                    "description": "注意：MySQL InnoDB 单列索引最大 3072 字节（utf8mb4 约 768 字符），且 LocalPath 上有唯一索引，因此长度限制为 768。",
                    "type": "string"
                },
                "maxDepth": {
                    "description": "最大监听深度，0 表示不限制",
                    "type": "integer"
                },
                "name": {
                    "description": "基本配置",
                    "type": "string"
                },
                "nextScanAt": {
                    "description": "预计下一次扫描时间（可选）",
                    "type": "string"
                },
                "remoteName": {
                    "description": "rclone remote 名称",
                    "type": "string"
                },
                "remotePath": {
                    "description": "远端路径",
                    "type": "string"
                },
                "scanIntervalSeconds": {
                    "description": "配置相关扩展",
                    "type": "integer"
                },
                "scanLeaseExpiresAt": {
                    "type": "string"
                },
                "scanLeaseOwner": {
                    "type": "string"
                },
                "status": {
                    "description": "状态信息",
                    "type": "string"
                },
                "syncType": {
                    "description": "同步类型",
                    "type": "string"
                },
                "totalFileCount": {
                    "description": "统计维度（便于分析与展示）",
                    "type": "integer"
                },
                "totalFileSize": {
                    "description": "当前已知文件总大小（字节）",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "uploadedBytes": {
                    "description": "累计已上传字节数",
                    "type": "integer"
                },
                "uploadedFileCount": {
                    "description": "累计已成功上传文件数",
                    "type": "integer"
                },
                "windowUploadedBytes": {
                    "description": "窗口内上传字节数",
                    "type": "integer"
                },
                "windowUploadedFiles": {
                    "description": "最近一段时间的窗口统计（可用于展示趋势）",
                    "type": "integer"
                }
            }
        },
        "rclone-sync-hub_internal_service.DashboardData": {
            "type": "object",
            "properties": {
                "by_status": {
                    "description": "ByStatus 按状态分布（饼图/柱状图）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rclone-sync-hub_internal_service.StatusItemVO"
                    }
                },
                "by_time": {
                    "description": "ByTime 按日趋势（折线图）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rclone-sync-hub_internal_service.TimeItemVO"
                    }
                },
                "by_watch_folder": {
                    "description": "ByWatchFolder 按监听文件夹分布（表格+柱状图）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rclone-sync-hub_internal_service.WatchFolderItemVO"
                    }
                },
                "items": {
                    "description": "Items 列表类数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.DashboardItemsVO"
                        }
                    ]
                },
                "overview": {
                    "description": "Overview 概览数字（卡片）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rclone-sync-hub_internal_service.OverviewVO"
                        }
                    ]
                }
            }
        },
        "rclone-sync-hub_internal_service.DashboardItemsVO": {
            "type": "object",
            "properties": {
                "failed_tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rclone-sync-hub_internal_model.UploadTask"
                    }
                },
                "recent_tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rclone-sync-hub_internal_model.UploadTask"
                    }
                }
            }
        },
        "rclone-sync-hub_internal_service.OverviewVO": {
            "type": "object",
            "properties": {
                "recent_24h_completed": {
                    "type": "integer"
                },
                "recent_24h_failed": {
                    "type": "integer"
                },
                "task_canceled": {
                    "type": "integer"
                },
                "task_failed": {
                    "type": "integer"
                },
                "task_paused": {
                    "type": "integer"
                },
                "task_pending": {
                    "type": "integer"
                },
                "task_running": {
                    "type": "integer"
                },
                "task_success": {
                    "type": "integer"
                },
                "task_total": {
                    "type": "integer"
                },
                "uploaded_bytes_total": {
                    "type": "integer"
                },
                "uploaded_files_total": {
                    "type": "integer"
                },
                "watch_folder_count": {
                    "type": "integer"
                }
            }
        },
        "rclone-sync-hub_internal_service.StatusItemVO": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "rclone-sync-hub_internal_service.TaskBatchResult": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ok_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "rclone-sync-hub_internal_service.TimeItemVO": {
            "type": "object",
            "properties": {
                "completed_count": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "failed_count": {
                    "type": "integer"
                },
                "uploaded_bytes": {
                    "type": "integer"
                }
            }
        },
        "rclone-sync-hub_internal_service.WatchFolderItemVO": {
            "type": "object",
            "properties": {
                "canceled_count": {
                    "type": "integer"
                },
                "failed_count": {
                    "type": "integer"
                },
                "paused_count": {
                    "type": "integer"
                },
                "pending_count": {
                    "type": "integer"
                },
                "running_count": {
                    "type": "integer"
                },
                "success_count": {
                    "type": "integer"
                },
                "task_count": {
                    "type": "integer"
                },
                "uploaded_bytes": {
                    "type": "integer"
                },
                "uploaded_files": {
                    "type": "integer"
                },
                "watch_folder_id": {
                    "type": "integer"
                },
                "watch_folder_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rclone Sync Hub API",
	Description:      "面向生产环境的本地文件扫描、持久化上传队列与 rclone 调度 API。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
